stages:
  - stop_containers
  - build
  - test
  - upload
  - start_containers
  
stop_containers:
  stage: stop_containers
  only:
    - master
  tags:
    - ddk.rest.api.client.stage
  script:
    - cd docker
    - sh update.sh
    - sh stop.sh
    
build:
  stage: build
  only:
    - master
  tags:
    - ddk.rest.api.client
  script:
    - sh build.sh

test:
  stage: test
  only:
    - master
  tags:
    - ddk.rest.api.client
  script:
    - cd docker
    - sh test.sh

upload:
  stage: upload
  only:
    - master
  tags:
    - ddk.rest.api.client
    - ddk.rest.api.client.stage
  script:
    - sh /root/DDK.Delegat.Install.Environment/DDK.REST.API.UPLOAD.IMAGE.sh
    - echo "Removing Docker images..."
    - sh docker/remove_images.sh
  when: manual

start_containers:
  stage: start_containers
  only:
    - master
  tags:
    - ddk.rest.api.client.stage
  script:
    - cd docker
    - sh start.sh
