version: "2"
services:
  ddk_rest_api_prod:
    build:
      dockerfile: prod.Dockerfile
      context: ../
    image: ddk_rest_api_prod
    container_name: ddk_rest_api_prod
    ports:
      - 7070:7070
    env_file:
      - .env
    restart: always
    command: node dist/bundle.js
